spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/device_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-1.0-device-note.xml
    enabled: true

server:
  port: 8080
